### ISSUE TITLE
Offer not multiplied with qty update in cart

### ISSUE THREAD

**Issue by techzotezo** [gaiterjones/magento-buy-x-get-y-free#14]
Hi,
This issue happens-Offer not multiplied with qty update in cart.

Suppose if we add 4 product or 3 products in the cart then he will get 4 or 3 products free.
but that is not working.

How to work that offer in that way?

Thanks.

**Comment by gaiterjones** [comment]
The module isn't designed to multiply the free Y products. You need to _create a Y product for each offer_ and then configure the module to add the corresponding Y product when the X qty is correct. i.e. create the following Y products "2 Free Widgets", "3 Free Widgets", "4 Free Widgets" then configure the module so that when you buy 3 of X you get the 3 Free Widgets Y product, 4 of X you get the 4 Free Widgets Y product etc. etc.

**Comment by techzotezo** [comment]
So each and every times needs to define offers buy 2 get 2 free,buy 3 get 3 free,buy 5 get 5 free individually?

Have there any way to define offer for all that at at a time?

Is it possible to customize?

**Comment by gaiterjones** [comment]
Unfortunately that is the way I designed the module, it is possible to change the logic in the script but I have no plans to update the module myself.

**Comment by techzotezo** [comment]
I want your help to customize this.Can you please share your skype id?

**Comment by techzotezo** [comment]
> 
it is possible to change the logic in the script
> 
I want you will change that functionality.If It needs to pay small payment I can ready to pay.
can you share your email id or skype id for future communication?
